(library
 (name visa_debugger)
 (public_name visa-debugger)
 (flags
  :standard
  -w
  +a-4-40-41-42-44-45-48-66
  -warn-error
  +a
  -open
  Base
  -open
  Cmdlang
  -open
  Pplumbing_log_cli)
 (libraries
  base
  bogue
  bopkit.visa
  bopkit.visa-assembler
  bopkit.visa-simulator
  bopkit.visa-syntax
  cmdlang
  fpath
  pplumbing-err
  pplumbing-log-cli)
 (lint
  (pps ppx_js_style -check-doc-comments))
 (preprocess
  (pps -unused-code-warnings=force ppx_let ppx_sexp_conv ppx_sexp_value)))
